### PR TITLE
Assert write permissions for output google buckets

### LINKED ISSUE #23: Fail fast if permissions are not correct for output paths
I created a data table for someone else to use with all the parameters needed for the cytomining workflow. When I tested it logged in as **a separate user**, the job failed after 4 hours because the data table mistakenly had a a GCS path in parameter `output_directory_gsurl` for which the separate user did not have WRITE permission.

Consider proactively checking that all output paths are writable before beginning computation, and fail fast when the permissions are incorrect. (If I recall correctly, Cromwell performs this check for intputs and outputs from GCS, this suite of workflows is not using Cromwell for file delocalization.) Thank you!

### PR DESCRIPTION
**Pull request by sjfleming**
Currently this is implemented as a separate utility task.

Closes #23

### CODE REVIEW

**Comment by deflaux** [comment]
Will this assertion occur for the cytomining workflow also?

**Review by carmendv — COMMENTED** [review]
Looks great! 
Just one comment
gcloud_assert_write_permission should also be included in the cytomining pipeline as @deflaux  suggested.

**Comment by carmendv** [comment]
Actually, the workflow is not working as it is. 
The task fails because "Array value was given but no 'sep' attribute was provided". [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/476ffa5b-a596-4268-a0bc-a2ba2c0a9f21) & [here](https://job-manager.dsde-prod.broadinstitute.org/jobs/999a8458-d59e-4f5d-957b-a8f96a337b67)

**Comment by sjfleming** [comment]
Totally forgot about that one, haha.
Also I haven’t yet tested to see if this actually works…

**Comment by sjfleming** [comment]
Ah okay I will fix that when I get a chance, thanks for testing

**Comment by sjfleming** [comment]
Okay I think this is ready to be tested @carmendv

**Comment by carmendv** [comment]
Alright I tested it.
You can find an example where the user has write access into the bucket for the output ([here](https://app.terra.bio/#workspaces/bayer-pcl-cell-imaging/pcl-live-imaging/job_history/1de6ab12-c424-443f-87d0-8e25a466d4f4)).
And one where the user lacks write permission ([here](https://app.terra.bio/#workspaces/bayer-pcl-cell-imaging/pcl-live-imaging/job_history/aca30766-b38f-4717-a445-77d3338d15ee)).

One question: Should `gcloud_assert_write_permission` task have an output, like the destination_gsurl if the gurls is a valid one, that will trigger the subsequent tasks? 
Otherwise, as it is right now, all the tasks get triggered and that could lead to unnecessary costs, specially for the scattered WDL's like this [one](https://job-manager.dsde-prod.broadinstitute.org/jobs/daee7f54-c9b4-4264-a2f8-e31b77d489f9).

**Comment by sjfleming** [comment]
Hmm, this is not working at all as I intended

**Comment by sjfleming** [comment]
There are two problems:
1. since the other WDL tasks do not depend on the output of `gcloud_assert_write_permission` (as you said), it seems like the other tasks run in parallel, rather than not running.  I did not know WDL worked this way.  This requires rethinking of the whole strategy... I wonder if there's a way to run this task first and require it to succeed...?  It also takes like 3.5 minutes to run, which seems a bit long.
2. The script is still not working correctly.  It seems like the task succeeded when the permission was right, but I think it succeeded by accident.  [This stderr log](https://00f74ba44b5875571a5446ef3de564e3df3b5f7af8-apidata.googleusercontent.com/download/storage/v1/b/fc-secure-190cf4d5-2ec2-402d-aee1-eb7b6494aaab/o/submissions%2F1de6ab12-c424-443f-87d0-8e25a466d4f4%2Fcreate_load_data%2Fc2ea8c85-2cde-4dcb-84b4-ef3342c35e67%2Fcall-gcloud_assert_write_permission%2Fstderr?jk=AFshE3V0XPtPMY51ms5gumq30qnGM80tIaPxcxqY2k5xWrbUCLanh3xEZvm9IOGq60hyDbBznlM1rX7eeMeQgPnvRhaHnvLTQ3hWvcYS9bJe3E8sn5xRbyvSvXfAUyZ9qlaTg3ryJZ4DhIQZpQBkml2rL0AB1Tke9IGr40Y9edbV6dmXJCLXdh2GyzLPXt_0cr_1JYT6BqXvlkwXqF7ZG34NIOYDoAXOJRFPPR9lEmxzz8-6E1T5cAz0g3u9ROeqmsVTvct9o3CMpjidEhjsj8Bo6SuFNUG7_5zGvDR-MY_rkQAFYqwkWCXLjmHTH9SO4MXZZx4CqKkz5U2i2KBu5WNFtza7ca6VBH10CXDXBJBTi6Ha_44gAq6YoByd7A8pxjhVBa0VMuyGFJ3rDVEL9VgtebaSXf0BKuTSrpWSs4VRKUlLQvgaCNzz2Lw6x0d174hAMs3UUVbb7xidco1CryFICT5ztewJrM8GIzpQmG4DkW_Hi_ie8iLgDP1Ax4NGWOBYuCr7fkJU5s-AIqnCfGViSplN7RHwNUiAxITYwxoaN2QEN0Bh_hWF4TLGRuUjnC9N2ytE861A2nGtd53YMYR5gW5s7a0T5MIvutfWjZ8h7q8j9yYjPuIvCAxsEQYEzwKiYbgdrwKkAxEP4W-2acvpIKWPH0yAw70NixSuCwgSu7FY7C4clqdgbd1C-kEH0bZ6qxRYJF4e-Hy3Wx2kIJutIyaRgC8Q3nxNrxjw_DvBrL9cIVCWBn-G4X1DPidt62sKnwGYtUANRaSOizJk69tHjj3PzZQMCmNJy4dWOfATVOGUls4BakFcq5-nPFr51hhC_iwEQf1pOWebfMZLhYS5zN-G5Mx1mbMyUJaaM9JBr15TKhYZahDn40GJg74HrYnu3aeVhJ9e2nUJOreBNUO4-HQecLdAFWFoNtLmuMOsg2FSJ3gVGemhFeNcRJQ4SvkkGfaBLvwtILH8VhwslV3YzUxNhmTsxz7No2wpOHILD9mq0EUjN-g_fnCxaM-ODW7vvePHhyc9YB4I6quCe8X8zXaNk8ppTnSxWhA_c_yfcb1HZEtfcBUFDX2diMVlS6Z3wbJBhFRNstSTSTuqYSFrrokmKjZr_lJVO6R5_IFze39935hVJG6LYXqOvIolbDwzZd2MohTAm5gmdv3OmrS6bjy8lWVKFs0O-csZMxoJcYOA_Nh7rVP8iQweY3AUOE6IvV3l2PWuirtA04M&isca=1) seems to show that my attempt to parse the json from google did not work.  It works for me locally, so this is confusing!  I need to take another look.

**Comment by sjfleming** [comment]
For the sake of expediency, I am tempted to close this for now in favor of #62 (assuming that #62 works)

**Pull request closed without merging**
