### PR TITLE
Add clarifications for max projection workflow and 'Delete intermediate results'.

### PR DESCRIPTION
**Pull request by deflaux**

### CODE REVIEW

**Comment by sjfleming** [comment]
I like it!

**Comment by sjfleming** [comment]
Let's see what @carmendv thinks

**Review by sjfleming — APPROVED** [review]
Nice!

**Review by carmendv — COMMENTED** [review]
Looks great! I agree!

**Comment by carmendv** [comment]
Merging this edits. Thanks 👍

**Pull request merged**
