### PR TITLE
Add image feature categories to cytomining.

### PR DESCRIPTION
**Pull request by deflaux**
This change adds more output columns to the results of cytomining. The results of this change match those in https://github.com/broadinstitute/cellprofiler-on-Terra/issues/76

For more detail, see:
* https://app.terra.bio/#workspaces/vts-playground/jump-cp-workflow-validation/job_history/9a3e2872-4751-44af-a4c4-b2d7ed3eb87e
* https://app.terra.bio/#workspaces/vts-playground/jump-cp-workflow-validation/analysis/launch/compare_cytomining_results.ipynb
* https://app.terra.bio/#workspaces/vts-playground/jump-cp-workflow-validation/analysis/launch/compare_cytomining_results_python.ipynb

### CODE REVIEW

**Review by sjfleming — APPROVED** [review]
Looks good to me!

**Comment by carmendv** [comment]
@deflaux Unfortunately, this change to add more inputs shouldn't be added as the default, because that will cause many other plates to fail.
If the Cellprofiler pipeline used to extract the features didn't measured one or more of the features listed in `IMAGE_FEATURE_CATEGORIES`, the code will fail returning an assertion error because those features are not present.
My suggestion is to keep `add_image_features` as `False` by default, but allowing to edit it and also the  `image_feature_categories` input optionally (same we do with aggregation_operation). 
Does that sound ok ?

**Comment by deflaux** [comment]
> @deflaux Unfortunately, this change to add more inputs shouldn't be added as the default, because that will cause many other plates to fail. If the Cellprofiler pipeline used to extract the features didn't measured one or more of the features listed in `IMAGE_FEATURE_CATEGORIES`, the code will fail returning an assertion error because those features are not present. My suggestion is to keep `add_image_features` as `False` by default, but allowing to edit it and also the `image_feature_categories` input optionally (same we do with aggregation_operation). Does that sound ok ?

Sounds good! Will do!

**Review by carmendv — COMMENTED** [review]
Great! Thanks!

**Review by carmendv — APPROVED** [review]
All good now, I also tested and works 👍

**Pull request merged**
